# Project information
site_name: 'MPS Service'
site_description: 'Management Presence Server (MPS) that will serve as the broker between the management console and the Intel® AMT clients'

# Repository
repo_name: 'open-amt-cloud-toolkit/MPS'
repo_url: 'https://github.com/open-amt-cloud-toolkit/MPS'

# Copyright
copyright: 'Copyright &copy; Intel Corporation 2019'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
    
# Page tree
nav:
  - Getting started: index.md
  - Activate AMT: activateAMT.md
  - API: api.md
  - Admin Methods: 
    - All Devices: methods/alldevices.md
    - Connected Devices: methods/connecteddevices.md
    - Disconnect: methods/disconnect.md
    - MEScript: methods/mescript.md
    - MPS Root Certificate: methods/rootcertificate.md
  - AMT Methods:
    - Audit log: methods/auditlog.md
    - Event log: methods/eventlog.md
    - General settings: methods/generalsettings.md
    - Hardware information: methods/hardwareinfo.md
    - Power action: methods/poweraction.md
    - Power capabilities: methods/powercapabilities.md
    - Power state: methods/powerstate.md
    - Version: methods/version.md
  - Types: 
    - Request body: https://open-amt-cloud-toolkit.github.io/MPS/methods/types/#requestbody
    - Response error body: https://open-amt-cloud-toolkit.github.io/MPS/methods/types/#responseerrorbody
    - Audit log: https://open-amt-cloud-toolkit.github.io/MPS/methods/types/#audit-log
    - Event log: https://open-amt-cloud-toolkit.github.io/MPS/methods/types/#event-log
    - General Settings: https://open-amt-cloud-toolkit.github.io/MPS/methods/types/#general-settings
    - Hardware information: https://open-amt-cloud-toolkit.github.io/MPS/methods/types/#hardware-information
    - Power action: https://open-amt-cloud-toolkit.github.io/MPS/methods/types/#power-action
    - Power capabilities: https://open-amt-cloud-toolkit.github.io/MPS/methods/types/#power-capabilities
    - Power state: https://open-amt-cloud-toolkit.github.io/MPS/methods/types/#power-state
    - Version: https://open-amt-cloud-toolkit.github.io/MPS/methods/types/#version
  - Release notes: release-notes.md
  
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
