# Project information
site_name: ActivEdge
# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Page tree
nav:
  - Home: index.md
  - Get Started with Microservices Locally:
    - Overview: Local/overview.md
    - Install MPS Locally: Local/installMPS.md
    - Install RPS Locally: Local/installRPS.md
    - Configure RPS: Local/configureRPS.md
    - Build RPC on a Managed Device: Local/buildRPC.md
    - Manage Device: Local/manageDevice.md
  - Deploy Microservices with Docker*:
    - Overview: Docker/overview.md
    - Build Docker* Images: Docker/dockerLocal.md
    - Configure RPS: Local/configureRPS.md
    - Build RPC on a Managed Device: Local/buildRPC.md
    - Manage Device: Local/manageDevice.md
  - Tutorials:
    - Docker Images on the Cloud: Docker/dockerCloud.md
    - Creating Consoles with the UI Toolkit: Tutorials/uitoolkit.md
    - Activating in ACM Mode: Tutorials/acmActivation.md
    - Adding a Database: Tutorials/addDatabase.md
    - Adding Vault Storage: Tutorials/addVault.md
    - Using a Whitelist: Tutorials/whitelist.md
  - APIs:
    - MPS Methods: APIs/indexMPS.md
    - RPS Methods: APIs/indexRPS.md
  - Topics:
    - Static and Dynamic IPs: Topics/misc.md
    - GUIDs in Intel AMT: Topics/guids.md
    - MEBX: Topics/mebx.md
    - Working with Proxies: Topics/proxies.md
    - Security Information: Topics/security.md
  - Release notes: release-notes.md
  - License: license.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true