# Project information
site_name: 'ActivEdge: Smart Building Blocks for Remote Edge Management'
# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Page tree
nav:
  - Home: index.md
  - Build and Deploy Microservices Locally:
    - Overview: Local/overview.md
    - Install MPS Locally: Local/installMPS.md
    - Install RPS Locally: Local/installRPS.md
  - Build and Deploy Microservices with Local Docker* Images:
    - Overview: Docker/overview.md
    - Build Docker* Images: Docker/dockerLocal.md
  - Configure RPS and Manage a Device with MPS:
    - Configure RPS: General/configureRPS.md
    - Build RPC on a Managed Device: General/buildRPC.md
    - Manage Device: General/manageDevice.md
  - Tutorials:
    - Docker Images on the Cloud: Docker/dockerCloud.md
    - Creating Consoles with the UI Toolkit: Tutorials/uitoolkit.md
    - Construct a Rest API Call: Tutorials/apiTutorial.md
    - Activating in ACM Mode: Tutorials/acmActivation.md
    - Adding a Database: Tutorials/addDatabase.md
    - Adding Vault Storage: Tutorials/addVault.md
    - Using an Allowlist: Tutorials/allowlist.md
  - APIs:
    - MPS Methods: APIs/indexMPS.md
    - RPS Methods: APIs/indexRPS.md
  - Topics:
    - Static and Dynamic IPs: Topics/misc.md
    - GUIDs in Intel AMT: Topics/guids.md
    - Manual Configuring and Unprovisioning: Topics/mebx.md
    - Working with Proxies: Topics/proxies.md
    - Security Information: Topics/security.md
  - Release notes: release-notes.md
  - License: license.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - attr_list
  - pymdownx.inlinehilite
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
