# Project information
site_name: 'ActivEdge: Smart Building Blocks for Remote Edge Management'
# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Page tree
nav:
  - Home: index.md
  - MPS & RPS Local Setup:
    - Overview: Local/overview.md
    - Install MPS Locally: Local/installMPS.md
    - Install RPS Locally: Local/installRPS.md
  - MPS & RPS Docker* Images:
    - Overview: Docker/overview.md
    - Build Docker* Images: Docker/dockerLocal.md
  - RPS Configuration:
    - Login to RPS: General/loginToRPS.md
    - Create a CIRA Config: General/createCIRAConfig.md
    - Create a Profile with CCM: General/createProfileCCM.md
    - Create a Profile with ACM: General/createProfileACM.md
  - RPC on a Managed Device:
    - Build & Run RPC: General/buildRPC.md
  - MPS Device Management:
    - See Connected Devices: General/manageDevice.md
  - Tutorials:
    - Docker Images on the Cloud: Docker/dockerCloud.md
    - Create Consoles with the UI Toolkit: Tutorials/uitoolkit.md
    - Construct a Rest API Call: Tutorials/apiTutorial.md
    - Add a Database: Tutorials/addDatabase.md
    - Add Vault Storage: Tutorials/addVault.md
    - Use an Allowlist: Tutorials/allowlist.md
  - APIs:
    - MPS Methods: APIs/indexMPS.md
    - RPS Methods: APIs/indexRPS.md
  - Security: security.md
  - ActivEdge Topics:
    - Static and Dynamic IPs: Topics/misc.md
    - GUIDs in Intel AMT: Topics/guids.md
    - Manually Configure and Unprovision: Topics/mebx.md
    - Proxies: Topics/proxies.md
  - Release notes: release-notes.md
  - License: license.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - attr_list
  - pymdownx.inlinehilite
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
