# Project information
site_name: 'MPS Service'
site_description: 'Management Presence Server (MPS) that will serve as the broker between the management console and the Intel® AMT clients'

# Repository
#repo_name: 'Danger-Bay/MPS_MicroService'
#repo_url: 'https://github.impcloud.net/Danger-Bay/MPS_MicroService'

# Copyright
copyright: 'Copyright &copy; Intel Corporation 2019'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
    
# Page tree
nav:
  - Activate AMT: activateAMT.md
  - Getting started: index.md
  - API: api.md
  - Admin Methods: 
    - All Devices: methods/alldevices.md
    - Connected Devices: methods/connecteddevices.md
    - Disconnect: methods/disconnect.md
    - MEScript: methods/mescript.md
    - MPS Root Certificate: methods/rootcertificate.md
  - AMT Methods:
    - Audit log: methods/auditlog.md
    - Event log: methods/eventlog.md
    - General settings: methods/generalsettings.md
    - Hardware information: methods/hardwareinfo.md
    - Power action: methods/poweraction.md
    - Power capabilities: methods/powercapabilities.md
    - Power state: methods/powerstate.md
    - Version: methods/version.md
  - Types: 
    - Request body: methods/types.md
    - Response error body: methods/types.md
    - Audit log: methods/types.md 
    - Event log: methods/types.md
    - General Settings: methods/types.md
    - Hardware information: methods/types.md
    - Power action: methods/types.md
    - Power capabilities: methods/types.md
    - Power state: methods/types.md
    - Version: methods/types.md
  - Release notes: release-notes.md
  - License: license.md
  
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
