#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
version: '3.3'
services: 
  rps:
    image: vprodemo/rps-microservice:${RPS_TAG}
    ports: 
      - "${WEBSOCKETPORT}:${WEBSOCKETPORT}"
      - "${RPS_WEB_PORT}:${RPS_WEB_PORT}"
    environment: 
      USEVAULT: ${USEVAULT}
      NODE_ENV: ${NODE_ENV}
      HTTPS: ${RPS_HTTPS}
      USE_DB_PROFILES: ${USE_DB_PROFILES}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WEBSOCKETTLS: ${WEBSOCKETTLS}
      WEB_PORT: ${RPS_WEB_PORT}
      WEBSOCKETPORT: ${WEBSOCKETPORT}
      RPSXAPIKEY: ${RPSXAPIKEY}
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      SECRETS_PATH: ${SECRETS_PATH}
      DEVELOPER_MODE: ${DEVELOPER_MODE}
      CREDENTIALS_PATH: ${RPS_CREDENTIALS_PATH}
      MPS_USER: ${MPS_USER}
      MPS_PASSWORD: ${MPS_PASSWORD}
      AMT_USER: ${AMT_USER}
      WEB_TLS_CERT: ${WEB_TLS_CERT}
      WEB_TLS_CERT_KEY: ${WEB_TLS_CERT_KEY}
    volumes:
            - app-volume:/config
  mps:
    image: vprodemo/mps-microservice:${MPS_TAG}
    ports: 
      - "${MPS_WEB_PORT}:${MPS_WEB_PORT}"
      - "${MPS_PORT}:${MPS_PORT}"
    environment: 
      GENERATE_CERTS: ${GENERATE_CERTS}
      CERT_COMMON_NAME: ${CERT_COMMON_NAME}
      NODE_ENV: ${NODE_ENV}
      USE_WHITELIST: ${USE_WHITELIST}
      MPS_PORT: ${MPS_PORT}
      WEB_PORT: ${MPS_WEB_PORT}
      MPS_USER: ${MPS_USER}
      MPS_PASSWORD: ${MPS_PASSWORD}
      USE_GLOBAL_CREDENTIALS: ${USE_GLOBAL_CREDENTIALS}
      ENABLE_LOGGING: ${ENABLE_LOGGING}
      DEBUG: ${DEBUG}
      USEVAULT: ${USEVAULT}
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      SECRETS_PATH: ${SECRETS_PATH}
      WEB_ADMIN_USER: ${WEB_ADMIN_USER}
      WEB_ADMIN_PASSWORD: ${WEB_ADMIN_PASSWORD}
      HTTPS: ${MPS_HTTPS}
      MPSXAPIKEY: ${MPSXAPIKEY}
      DEVELOPER_MODE: ${DEVELOPER_MODE}
      WEB_ADMIN_USER: ${WEB_ADMIN_USER}
      WEB_ADMIN_PASSWORD: ${WEB_ADMIN_PASSWORD}
      CREDENTIALS_PATH: ${CREDENTIALS_PATH}
      GUIDS_PATH: ${GUIDS_PATH}
      ORGS_PATH: ${ORGS_PATH}
      LISTEN_ANY: ${LISTEN_ANY}
      MPS_TLS_OFFLOAD: ${MPS_TLS_OFFLOAD}
      MPS_SESSION_ENCRYPTION_KEY: ${MPS_SESSION_ENCRYPTION_KEY}
    volumes:
            - app-volume:/config
volumes:
    app-volume: