#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-mpsserver
spec:
  replicas: {{ .Values.mps.replicaCount }}
  selector:
    matchLabels:
      app: azure-mpsserver
  template:
    metadata:
      labels:
        app: azure-mpsserver
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.pullSecret }}
      containers:
      - name: azure-mpsserver
        image: {{ .Values.images.mps }}
        env:
          - name: "DEVELOPER_MODE"
            value: "{{ .Values.mps.devmode }}"
          - name: "GENERATE_CERTS"
            value: "{{ .Values.mps.generateCerts }}"
          - name: "NODE_ENV"
            value: "{{ .Values.mps.nodeEnv }}"
          - name: "CERT_COMMON_NAME"
            value: "{{ .Values.mps.certCommonName }}"
          - name: "SERVER_DEPLOYMENT_MODE"
            value: "{{ .Values.mps.serverDeploymentMode }}"
          - name: "USE_WHITELIST"
            value: "{{ .Values.mps.useWhiteList }}"
          - name: "MPS_PORT"
            value: "{{ .Values.mps.mpsPort }}"
          - name: "WEB_PORT"
            value: "{{ .Values.mps.webPort }}"
          - name: "MPS_USER"
            value: "{{ .Values.mps.mpsUser }}"
          - name: "MPS_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.creds }}
                key: {{ .Values.mps.mpsPassword }}
          - name: "USE_GLOBAL_CREDENTIALS"
            value: "{{ .Values.mps.useGlobalCredentials }}"
          - name: "ENABLE_LOGGING"
            value: "{{ .Values.mps.enableLogging }}"
          - name: "DEBUG"
            value: "{{ .Values.mps.debug }}"
          - name: "USEVAULT"
            value: "{{ .Values.mps.useVault }}"
          - name: "VAULT_ADDR"
            value : "{{ .Values.mps.vaultAddr }}"
          - name: "SECRETS_PATH"
            value: "{{ .Values.mps.secretsPath }}"
          - name: "DEBUG_LEVEL"
            value: "{{ .Values.mps.debugLevel }}"
          - name: "WEB_ADMIN_USER"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.web }}
                key: {{ .Values.mps.webAdminUserKey }}
          - name: "WEB_ADMIN_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.web }}
                key: {{ .Values.mps.webAdminPasswordKey }}
          - name: MPSXAPIKEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.api }}
                key: {{ .Values.mps.apikeyKeyName }}
          - name: MPS_TLS_CERT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.certs }}
                key: {{ .Values.mps.mpscertpublic }}
          - name: MPS_TLS_CERT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.certs }}
                key: {{ .Values.mps.mpscertkey }}
          - name: WEB_TLS_CERT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.certs }}
                key: {{ .Values.mps.webcertpublic }}
          - name: WEB_TLS_CERT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.certs }}
                key: {{ .Values.mps.webcertkey }}
          - name: ROOT_CA_CERT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.certs }}
                key: {{ .Values.mps.rootcacert }}
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.vault }}
                key: {{ .Values.mps.vaultkey }}
          - name: MPS_SESSION_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.session }}
                key: {{ .Values.mps.sessionEncryptionKey }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 784Mi
        ports:
        - containerPort: {{ .Values.mps.mpsPort }}
          name: mps
        - containerPort: {{ .Values.mps.webPort }}
          name: web