#*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#*********************************************************************/

name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      docker_tag_name:
            description: 'Tag you wish to use on the docker image. Image will always be tagged with commit SHA'     
            required: false
            default: 'mps:v1'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.inputs.docker_tag_name }} --tag ${{ secrets.DOCKER_REGISTRY }}/${{github.event.head_commit.message}}
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: true
    - name: Push the Docker image to the registry
      run: docker push --all-tags ${{ github.event.inputs.docker_registry }}/${{ github.event.inputs.docker_tag_name }}

